spring.application.name=url-shortener-sb

# ===============================
# MySQL Database
# ===============================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ===============================
# JWT
# ===============================
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:172800000}

# ===============================
# Frontend
# ===============================
frontend.url=${FRONTEND_URL:http://localhost:5173}

# ===============================
# Server
# ===============================
server.port=${PORT:10000}

# ===============================
# Logging
# ===============================
logging.level.org.springframework.security=INFO
logging.level.org.url.shortener=INFO
logging.level.org.springframework.web=INFO
